# 变量 | 模板
info-filter: &info-filter "(?i)套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|如果|更新"
cn-dns: &cn-dns
  - 223.5.5.5
  - 119.29.29.29
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
non-cn-dns: &non-cn-dns
  - 8.8.8.8
  - 1.1.1.1
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
proxy-provider-template: &proxy-provider-template
  type: http
  interval: 43200
  proxy: DIRECT
  header:
    User-Agent:
      - "clash.meta"
      - "mihomo/1.19.24"
  health-check:
    enable: true
    lazy: false
    url: https://www.gstatic.com/generate_204
    interval: 300
    timeout: 5000

# mihomo配置
mode: rule
# IPv6 总开关
ipv6: true
log-level: warning
find-process-mode: strict
unified-delay: true
tcp-concurrent: true
# 代理端口
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
# TUN 模式
tun:
  enable: false
  device: mihomo
  stack: mixed
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  disable-icmp-forwarding: true
# DNS 配置
dns:
  enable: true
  cache-algorithm: arc
  listen: "[::]:1053"
  # 是否解析 IPv6
  ipv6: true
  direct-nameserver: *cn-dns
  nameserver-policy:
    "geosite:cn,private": *cn-dns
    "geosite:win-update": *cn-dns
    "geosite:geolocation-!cn": *non-cn-dns
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "geosite:private"
    - "geosite:category-ntp"
    - "geosite:connectivity-check"
    - "geosite:tracker"
    - "geosite:cn"
    - +.qianmobai.top
  fake-ip-filter-mode: blacklist
# 代理集
proxy-providers:
  provider1:
    <<: *proxy-provider-template
    # 填写订阅地址
    url:
# 代理组
proxy-groups:
  - name: 节点选择
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png"
    proxies:
      - 自动切换
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 手动切换
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png"
    include-all: true
    exclude-filter: *info-filter
  - name: 自动切换
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png"
    url: https://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    exclude-filter: *info-filter
  - name: 故障转移
    type: fallback
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Magic.png"
    url: https://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    exclude-filter: *info-filter
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Stack.png"
    url: https://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    exclude-filter: *info-filter
  - name: Ai平台
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AI.png"
    proxies:
      - 节点选择
      - 自动切换
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: Win更新
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Windows.png"
    proxies:
      - DIRECT
      - REJECT
  - name: 哔哩哔哩
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png"
    proxies:
      - DIRECT
      - 台湾节点
      - 香港节点
  - name: 谷歌FCM
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 游戏平台
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 香港节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png"
    url: "https://www.gstatic.com/generate_204"
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)港|HK|hk|Hong Kong|HongKong|hongkong"
  - name: 日本节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png"
    url: https://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan"
  - name: 美国节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png"
    url: https://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  - name: 台湾节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png"
    include-all: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    filter: "(?i)台|新北|彰化|TW|Taiwan"
  - name: 狮城节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png"
    include-all: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    filter: "(?i)新加坡|坡|狮城|SG|Singapore"
  - name: 韩国节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png"
    url: https://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)KR|Korea|KOR|首尔|韩|韓"
  - name: 漏网之鱼
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png"
    proxies:
      - 节点选择
      - 自动切换
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 订阅信息
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Airport.png"
    include-all: true
    filter: *info-filter
  - name: GLOBAL
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png"
    proxies:
      - DIRECT
    include-all: true
    exclude-filter: *info-filter
# 规则
rules:
  # RULE-SET
  - RULE-SET,mobai-direct,DIRECT
  # GEOSITE
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,connectivity-check,DIRECT
  - GEOSITE,category-ntp,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,tracker,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,win-update,Win更新
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,steam,游戏平台
  - GEOSITE,epicgames,游戏平台
  - GEOSITE,ea,游戏平台
  - GEOSITE,openai,Ai平台
  - GEOSITE,category-ai-!cn,Ai平台
  - GEOSITE,googlefcm,谷歌FCM
  - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,biliintl,哔哩哔哩
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,节点选择
  # GEOIP
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,漏网之鱼
# 规则集
rule-providers:
  mobai-direct:
    type: http
    behavior: classical
    format: yaml
    url: "https://testingcf.jsdelivr.net/gh/Qian-MoBai/proxy/mihomo/rules/direct.yaml"
    interval: 43200
    proxy: DIRECT
# 外部控制
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-name:
external-ui-url: "https://gh-proxy.org/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
profile:
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-selected: false
  # 储存 fakeip 映射表
  store-fake-ip: true
# GeoSite
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 12
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
